      SUBROUTINE CTEMG2(FCANCMXGAT,     RMATCGAT,      ZOLNCGAT,
     1      PAICGAT,
     1      AILCGAT,     AILCGGAT,    CMASVEGCGAT,     SLAICGAT,
     2      AILCGSGAT,   FCANCSGAT,   FCANCGAT,     RMATCTEMGAT,
     3      CO2CONCGAT,  CO2I1CGGAT,  CO2I1CSGAT,   CO2I2CGGAT, 
     4      CO2I2CSGAT,  XDIFFUSGAT,  SLAIGAT,      CFLUXCGGAT, 
     5      CFLUXCSGAT,  ANCSVEGGAT,  ANCGVEGGAT,   RMLCSVEGGAT,
     6      RMLCGVEGGAT, CANRESGAT,   SDEPGAT,
     7      SANDGAT,     CLAYGAT,     ORGMGAT,
     8      ANVEGGAT,    RMLVEGGAT,   TCANOACCGAT_M,TBARACCGAT_M,
     9      UVACCGAT_M,  VVACCGAT_M,  MLIGHTNGGAT,  PRBFRHUCGAT,
     A      EXTNPROBGAT, STDALNGAT,   PFCANCMXGAT,  NFCANCMXGAT,
     B      STEMMASSGAT, ROOTMASSGAT, LITRMASSGAT,  GLEAFMASGAT,
     C      BLEAFMASGAT, SOILCMASGAT, AILCBGAT,     FLHRLOSSGAT,
     D      PANDAYSGAT,  LFSTATUSGAT, GRWTHEFFGAT,  LYSTMMASGAT,
     E      LYROTMASGAT, TYMAXLAIGAT, VGBIOMASGAT,  GAVGLTMSGAT,
     F      STMHRLOSGAT, BMASVEGGAT,  COLDDAYSGAT,  ROTHRLOSGAT,
     G      ALVSCTMGAT,  ALIRCTMGAT,  GAVGLAIGAT,   NPPGAT,
     H      NEPGAT,      HETRORESGAT, AUTORESGAT,   SOILRESPGAT,
     I      RMGAT,       RGGAT,       NBPGAT,       LITRESGAT,
     J      SOCRESGAT,   GPPGAT,      DSTCEMLSGAT,  LITRFALLGAT,
     K      HUMIFTRSGAT, VEGHGHTGAT,  ROOTDPTHGAT,  RMLGAT,
     L      RMSGAT,      RMRGAT,      TLTRLEAFGAT,  TLTRSTEMGAT,
     M      TLTRROOTGAT, LEAFLITRGAT, ROOTTEMPGAT,  AFRLEAFGAT,
     N      AFRSTEMGAT,  AFRROOTGAT,  WTSTATUSGAT,  LTSTATUSGAT,
     O      BURNFRACGAT, PROBFIREGAT, LUCEMCOMGAT,  LUCLTRINGAT,
     P      LUCSOCINGAT, NPPVEGGAT,   GRCLAREAGAT,  DSTCEMLS3GAT,
     Q      FAREGAT,     GAVGSCMSGAT, RMLVEGACCGAT,
     R      RMSVEGGAT,   RMRVEGGAT,   RGVEGGAT,    VGBIOMAS_VEGGAT,
     S      GPPVEGGAT,   NEPVEGGAT,   AILCMINGAT,   AILCMAXGAT,
     T      EMIT_CO2GAT,  EMIT_COGAT, EMIT_CH4GAT,  EMIT_NMHCGAT,
     U      EMIT_H2GAT,   EMIT_NOXGAT,EMIT_N2OGAT,  EMIT_PM25GAT,
     V      EMIT_TPMGAT,  EMIT_TCGAT, EMIT_OCGAT,   EMIT_BCGAT,
C
     R      ILMOS,       JLMOS,       IWMOS,        JWMOS,
     S      NML,         NLAT,        NMOS,         ILG, 
     T      IGND,        ICAN,        ICP1,         ICC,
     U      FCANCMXROW,  RMATCROW,    ZOLNCROW,     PAICROW,
     V      AILCROW,     AILCGROW,    CMASVEGCROW,  SLAICROW,
     W      AILCGSROW,   FCANCSROW,   FCANCROW,     RMATCTEMROW,
     X      CO2CONCROW,  CO2I1CGROW,  CO2I1CSROW,   CO2I2CGROW,
     Y      CO2I2CSROW,  XDIFFUS,     SLAIROW,      CFLUXCGROW,
     Z      CFLUXCSROW,  ANCSVEGROW,  ANCGVEGROW,   RMLCSVEGROW,
     1      RMLCGVEGROW, CANRESROW,   SDEPROW,
     2      SANDROW,     CLAYROW,     ORGMROW,
     3      ANVEGROW,    RMLVEGROW,   TCANOACCROW_M,TBARACCROW_M,
     4      UVACCROW_M,  VVACCROW_M,  MLIGHTNGGRD,  PRBFRHUCGRD,
     5      EXTNPROBGRD, STDALNGRD,   PFCANCMXROW,  NFCANCMXROW,
     6      STEMMASSROW, ROOTMASSROW, LITRMASSROW,  GLEAFMASROW,
     7      BLEAFMASROW, SOILCMASROW, AILCBROW,     FLHRLOSSROW,
     8      PANDAYSROW,  LFSTATUSROW, GRWTHEFFROW,  LYSTMMASROW,
     9      LYROTMASROW, TYMAXLAIROW, VGBIOMASROW,  GAVGLTMSROW,
     A      STMHRLOSROW, BMASVEGROW,  COLDDAYSROW,  ROTHRLOSROW,
     B      ALVSCTMROW,  ALIRCTMROW,  GAVGLAIROW,   NPPROW,
     C      NEPROW,      HETRORESROW, AUTORESROW,   SOILRESPROW,
     D      RMROW,       RGROW,       NBPROW,       LITRESROW,
     E      SOCRESROW,   GPPROW,      DSTCEMLSROW,  LITRFALLROW,
     F      HUMIFTRSROW, VEGHGHTROW,  ROOTDPTHROW,  RMLROW,
     G      RMSROW,      RMRROW,      TLTRLEAFROW,  TLTRSTEMROW,
     H      TLTRROOTROW, LEAFLITRROW, ROOTTEMPROW,  AFRLEAFROW,
     I      AFRSTEMROW,  AFRROOTROW,  WTSTATUSROW,  LTSTATUSROW,
     J      BURNFRACROW, PROBFIREROW, LUCEMCOMROW,  LUCLTRINROW,
     K      LUCSOCINROW, NPPVEGROW,   GRCLAREAROW,  DSTCEMLS3ROW,
     L      FAREROW,     GAVGSCMSROW, RMLVEGACCROW,
     &      RMSVEGROW,   RMRVEGROW,   RGVEGROW,   VGBIOMAS_VEGROW,
     &      GPPVEGROW,   NEPVEGROW,  AILCMINROW,   AILCMAXROW,
     &      EMIT_CO2ROW,  EMIT_COROW, EMIT_CH4ROW,  EMIT_NMHCROW,
     &      EMIT_H2ROW,   EMIT_NOXROW,EMIT_N2OROW,  EMIT_PM25ROW,
     &      EMIT_TPMROW,  EMIT_TCROW, EMIT_OCROW,   EMIT_BCROW )
C
C              CANADIAN TERRESTRIAL ECOSYSTEM MODEL (CTEM) V1.1
C
C     July 28 2009    GATHER OPERATION ON CTEM VARIABLES.
C     RONG LI
C 
      IMPLICIT NONE
C
C     * INTEGER CONSTANTS.
C
      INTEGER  NML, NLAT, NMOS, ILG, IGND, ICAN, ICP1, K, L, M
      INTEGER  ICC
C
C     * GATHER-SCATTER INDEX ARRAYS.
C
      INTEGER  ILMOS (ILG),  JLMOS  (ILG),  IWMOS  (ILG),  JWMOS (ILG)
C
C
      REAL  FCANCMXGAT(ILG,ICC),      RMATCGAT(ILG,ICAN,IGND),
     1      ZOLNCGAT(ILG,ICAN),       PAICGAT(ILG,ICAN),
     2      AILCGAT(ILG,ICAN),        AILCGGAT(ILG,ICC),
     3      CMASVEGCGAT(ILG,ICAN),    SLAICGAT(ILG,ICAN),
     4      AILCGSGAT(ILG,ICC),       FCANCSGAT(ILG,ICC),
     5      FCANCGAT(ILG,ICC),        RMATCTEMGAT(ILG,ICC,IGND),
     6      CO2CONCGAT(ILG),          CO2I1CGGAT(ILG,ICC),
     7      CO2I1CSGAT(ILG,ICC),      CO2I2CGGAT(ILG,ICC),
     8      CO2I2CSGAT(ILG,ICC),      XDIFFUSGAT(ILG),
     9      SLAIGAT(ILG,ICC),         CFLUXCGGAT(ILG),
     A      CFLUXCSGAT(ILG),          ANCSVEGGAT(ILG,ICC),
     B      ANCGVEGGAT(ILG,ICC),      RMLCSVEGGAT(ILG,ICC),
     C      RMLCGVEGGAT(ILG,ICC),     CANRESGAT(ILG),
     D      SDEPGAT(ILG)
C
      REAL    SANDGAT(ILG,IGND),      CLAYGAT(ILG,IGND), 
     1        ORGMGAT(ILG,IGND)
C
      REAL    ANVEGGAT(ILG,ICC),      RMLVEGGAT(ILG,ICC)
C
      REAL   TCANOACCGAT_M(ILG),
     1          UVACCGAT_M(ILG),      VVACCGAT_M(ILG)
C
      REAL   MLIGHTNGGAT(ILG,12)  !12MONTH
C
      REAL  PRBFRHUCGAT(ILG),         EXTNPROBGAT(ILG),
     1      TBARACCGAT_M(ILG,IGND),
     2      PFCANCMXGAT(ILG,ICC),     NFCANCMXGAT(ILG,ICC),
     3      STEMMASSGAT(ILG,ICC),     ROOTMASSGAT(ILG,ICC),  
     4      LITRMASSGAT(ILG,ICC+1),   GLEAFMASGAT(ILG,ICC),
     5      BLEAFMASGAT(ILG,ICC),     SOILCMASGAT(ILG,ICC+1),
     6      AILCBGAT(ILG,ICC),        FLHRLOSSGAT(ILG,ICC)
C
      INTEGER  PANDAYSGAT(ILG,ICC),   LFSTATUSGAT(ILG,ICC),
     1         STDALNGAT(ILG),       COLDDAYSGAT(ILG,2)
C
      REAL  GRWTHEFFGAT(ILG,ICC),    LYSTMMASGAT(ILG,ICC),
     9      LYROTMASGAT(ILG,ICC),    TYMAXLAIGAT(ILG,ICC),
     A      VGBIOMASGAT(ILG),        GAVGLTMSGAT(ILG),
     B      STMHRLOSGAT(ILG,ICC),    BMASVEGGAT(ILG,ICC),
     C      ROTHRLOSGAT(ILG,ICC),
     D      ALVSCTMGAT(ILG,ICAN),    ALIRCTMGAT(ILG,ICAN),
     E      GAVGLAIGAT(ILG)
C
      REAL  NPPGAT(ILG),            NEPGAT(ILG),
     1      HETRORESGAT(ILG),       AUTORESGAT(ILG),
     2      SOILRESPGAT(ILG),       RMGAT(ILG),     RGGAT(ILG),
     3      NBPGAT(ILG),            LITRESGAT(ILG),
     4      SOCRESGAT(ILG),         GPPGAT(ILG),
     5      DSTCEMLSGAT(ILG),       LITRFALLGAT(ILG),
     6      HUMIFTRSGAT(ILG),       VEGHGHTGAT(ILG,ICC),
     7      ROOTDPTHGAT(ILG,ICC),   RMLGAT(ILG),
     8      RMSGAT(ILG),            RMRGAT(ILG),
     9      TLTRLEAFGAT(ILG,ICC),   TLTRSTEMGAT(ILG,ICC),
     A      TLTRROOTGAT(ILG,ICC),   LEAFLITRGAT(ILG,ICC),
     B      ROOTTEMPGAT(ILG,ICC),   AFRLEAFGAT(ILG,ICC),
     C      AFRSTEMGAT(ILG,ICC),    AFRROOTGAT(ILG,ICC),
     D      WTSTATUSGAT(ILG,ICC),   LTSTATUSGAT(ILG,ICC),
     E      BURNFRACGAT(ILG),       PROBFIREGAT(ILG),
     F      LUCEMCOMGAT(ILG),       LUCLTRINGAT(ILG),
     G      LUCSOCINGAT(ILG),       NPPVEGGAT(ILG,ICC),
     H      GRCLAREAGAT(ILG),       DSTCEMLS3GAT(ILG)
C
C      FIRE EMISSION VARIABLES
       REAL EMIT_CO2GAT(ILG),  EMIT_COGAT(ILG), 
     1      EMIT_CH4GAT(ILG),  EMIT_NMHCGAT(ILG),
     2      EMIT_H2GAT(ILG),   EMIT_NOXGAT(ILG),
     3      EMIT_N2OGAT(ILG),  EMIT_PM25GAT(ILG),
     4      EMIT_TPMGAT(ILG),  EMIT_TCGAT(ILG),
     5      EMIT_OCGAT(ILG),   EMIT_BCGAT(ILG)
C
      REAL  FAREGAT(ILG)
      REAL  GAVGSCMSGAT(ILG)
C
      REAL RMLVEGACCGAT(ILG,ICC),       RMSVEGGAT(ILG,ICC),
     1      RMRVEGGAT(ILG,ICC),         RGVEGGAT(ILG,ICC),
     2      AILCMINGAT(ILG,ICC),        AILCMAXGAT(ILG,ICC)
C
      REAL VGBIOMAS_VEGGAT(ILG,ICC)
C
      REAL GPPVEGGAT(ILG,ICC),        NEPVEGGAT(ILG,ICC)
C
      REAL  FCANCMXROW(NLAT,NMOS,ICC),   RMATCROW(NLAT,NMOS,ICAN,IGND),
     1      ZOLNCROW(NLAT,NMOS,ICAN),    PAICROW(NLAT,NMOS,ICAN),
     2      AILCROW(NLAT,NMOS,ICAN),     AILCGROW(NLAT,NMOS,ICC),
     3      CMASVEGCROW(NLAT,NMOS,ICAN), SLAICROW(NLAT,NMOS,ICAN),
     4      AILCGSROW(NLAT,NMOS,ICC),    FCANCSROW(NLAT,NMOS,ICC),
     5      FCANCROW(NLAT,NMOS,ICC),    RMATCTEMROW(NLAT,NMOS,ICC,IGND),
     6      CO2CONCROW(NLAT,NMOS),       CO2I1CGROW(NLAT,NMOS,ICC),
     7      CO2I1CSROW(NLAT,NMOS,ICC),   CO2I2CGROW(NLAT,NMOS,ICC),
     8      CO2I2CSROW(NLAT,NMOS,ICC),   XDIFFUS(NLAT),
     9      SLAIROW(NLAT,NMOS,ICC),      CFLUXCGROW(NLAT,NMOS),
     A      CFLUXCSROW(NLAT,NMOS),       ANCSVEGROW(NLAT,NMOS,ICC),
     B      ANCGVEGROW(NLAT,NMOS,ICC),   RMLCSVEGROW(NLAT,NMOS,ICC),
     C      RMLCGVEGROW(NLAT,NMOS,ICC),  CANRESROW(NLAT,NMOS),
     D      SDEPROW(NLAT,NMOS)
C
      REAL    SANDROW(NLAT,NMOS,IGND),   CLAYROW(NLAT,NMOS,IGND), 
     1        ORGMROW(NLAT,NMOS,IGND)
C
      REAL  ANVEGROW(NLAT,NMOS,ICC),     RMLVEGROW(NLAT,NMOS,ICC)
C
      REAL  TCANOACCROW_M(NLAT,NMOS),
     1      UVACCROW_M(NLAT,NMOS),       VVACCROW_M(NLAT,NMOS)
C
      REAL  MLIGHTNGGRD(NLAT,12)  !12MONTH
C
      REAL  PRBFRHUCGRD(NLAT),            EXTNPROBGRD(NLAT),
     1      TBARACCROW_M(NLAT,NMOS,IGND),
     2      PFCANCMXROW(NLAT,NMOS,ICC),   NFCANCMXROW(NLAT,NMOS,ICC),
     3      STEMMASSROW(NLAT,NMOS,ICC),   ROOTMASSROW(NLAT,NMOS,ICC),
     4      LITRMASSROW(NLAT,NMOS,ICC+1), GLEAFMASROW(NLAT,NMOS,ICC),
     5      BLEAFMASROW(NLAT,NMOS,ICC),   SOILCMASROW(NLAT,NMOS,ICC+1),
     6      AILCBROW(NLAT,NMOS,ICC),      FLHRLOSSROW(NLAT,NMOS,ICC)
C
      INTEGER PANDAYSROW(NLAT,NMOS,ICC),  LFSTATUSROW(NLAT,NMOS,ICC),
     1      STDALNGRD(NLAT),COLDDAYSROW(NLAT,NMOS,2)

C
      REAL  GRWTHEFFROW(NLAT,NMOS,ICC),    LYSTMMASROW(NLAT,NMOS,ICC),
     9      LYROTMASROW(NLAT,NMOS,ICC),    TYMAXLAIROW(NLAT,NMOS,ICC),
     A      VGBIOMASROW(NLAT,NMOS),        GAVGLTMSROW(NLAT,NMOS),
     B      STMHRLOSROW(NLAT,NMOS,ICC),    BMASVEGROW(NLAT,NMOS,ICC),
     C      ROTHRLOSROW(NLAT,NMOS,ICC),
     D      ALVSCTMROW(NLAT,NMOS,ICAN),    ALIRCTMROW(NLAT,NMOS,ICAN),
     E      GAVGLAIROW(NLAT,NMOS)
C
      REAL  NPPROW(NLAT,NMOS),             NEPROW(NLAT,NMOS),
     1      HETRORESROW(NLAT,NMOS),        AUTORESROW(NLAT,NMOS),
     2      SOILRESPROW(NLAT,NMOS),        RMROW(NLAT,NMOS),
     2      RGROW(NLAT,NMOS),
     3      NBPROW(NLAT,NMOS),             LITRESROW(NLAT,NMOS),
     4      SOCRESROW(NLAT,NMOS),          GPPROW(NLAT,NMOS),
     5      DSTCEMLSROW(NLAT,NMOS),        LITRFALLROW(NLAT,NMOS),
     6      HUMIFTRSROW(NLAT,NMOS),        VEGHGHTROW(NLAT,NMOS,ICC),
     7      ROOTDPTHROW(NLAT,NMOS,ICC),    RMLROW(NLAT,NMOS),
     8      RMSROW(NLAT,NMOS),             RMRROW(NLAT,NMOS),
     9      TLTRLEAFROW(NLAT,NMOS,ICC),    TLTRSTEMROW(NLAT,NMOS,ICC),
     A      TLTRROOTROW(NLAT,NMOS,ICC),    LEAFLITRROW(NLAT,NMOS,ICC),
     B      ROOTTEMPROW(NLAT,NMOS,ICC),    AFRLEAFROW(NLAT,NMOS,ICC),
     C      AFRSTEMROW(NLAT,NMOS,ICC),     AFRROOTROW(NLAT,NMOS,ICC),
     D      WTSTATUSROW(NLAT,NMOS,ICC),    LTSTATUSROW(NLAT,NMOS,ICC),
     E      BURNFRACROW(NLAT,NMOS),        PROBFIREROW(NLAT,NMOS),
     F      LUCEMCOMROW(NLAT,NMOS),        LUCLTRINROW(NLAT,NMOS),
     G      LUCSOCINROW(NLAT,NMOS),        NPPVEGROW(NLAT,NMOS,ICC),
     H      GRCLAREAROW(NLAT,NMOS),        DSTCEMLS3ROW(NLAT,NMOS)
C
C     FIRE EMISSION VARIABLES
      REAL EMIT_CO2ROW(NLAT,NMOS),  EMIT_COROW(NLAT,NMOS), 
     1     EMIT_CH4ROW(NLAT,NMOS),  EMIT_NMHCROW(NLAT,NMOS),
     2     EMIT_H2ROW(NLAT,NMOS),   EMIT_NOXROW(NLAT,NMOS),
     3     EMIT_N2OROW(NLAT,NMOS),  EMIT_PM25ROW(NLAT,NMOS),
     4     EMIT_TPMROW(NLAT,NMOS),  EMIT_TCROW(NLAT,NMOS),
     5     EMIT_OCROW(NLAT,NMOS),   EMIT_BCROW(NLAT,NMOS)
C
      REAL  FAREROW(NLAT,NMOS)
C
      REAL  GAVGSCMSROW(NLAT,NMOS)
C
      REAL RMLVEGACCROW(NLAT,NMOS,ICC), RMSVEGROW(NLAT,NMOS,ICC),
     1      RMRVEGROW(NLAT,NMOS,ICC),   RGVEGROW(NLAT,NMOS,ICC),
     2      AILCMINROW(NLAT,NMOS,ICC),  AILCMAXROW(NLAT,NMOS,ICC)
C
      REAL VGBIOMAS_VEGROW(NLAT,NMOS,ICC)
C
      REAL GPPVEGROW(NLAT,NMOS,ICC),    NEPVEGROW(NLAT,NMOS,ICC)
C
C----------------------------------------------------------------------
      DO 100 K=1,NML
          SDEPGAT(K)      = SDEPROW(ILMOS(K),JLMOS(K))
          CO2CONCGAT(K)   = CO2CONCROW(ILMOS(K),JLMOS(K))
          CFLUXCGGAT(K)   = CFLUXCGROW(ILMOS(K),JLMOS(K))
          CFLUXCSGAT(K)   = CFLUXCSROW(ILMOS(K),JLMOS(K))
          CANRESGAT(K)    = CANRESROW(ILMOS(K),JLMOS(K))
          XDIFFUSGAT(K)   = XDIFFUS(ILMOS(K))
          PRBFRHUCGAT(K)  = PRBFRHUCGRD(ILMOS(K))
          EXTNPROBGAT(K)  = EXTNPROBGRD(ILMOS(K))
          STDALNGAT(K)    = STDALNGRD(ILMOS(K))
          TCANOACCGAT_M(K)= TCANOACCROW_M(ILMOS(K),JLMOS(K))
          UVACCGAT_M(K)   = UVACCROW_M(ILMOS(K),JLMOS(K))
          VVACCGAT_M(K)   = VVACCROW_M(ILMOS(K),JLMOS(K))
          VGBIOMASGAT(K)  = VGBIOMASROW(ILMOS(K),JLMOS(K))
          GAVGLTMSGAT(K)  = GAVGLTMSROW(ILMOS(K),JLMOS(K))
          GAVGLAIGAT(K)   = GAVGLAIROW(ILMOS(K),JLMOS(K))
          NPPGAT(K)       = NPPROW(ILMOS(K),JLMOS(K))
          NEPGAT(K)       = NEPROW(ILMOS(K),JLMOS(K))
          HETRORESGAT(K)  = HETRORESROW(ILMOS(K),JLMOS(K))
          AUTORESGAT(K)   = AUTORESROW(ILMOS(K),JLMOS(K))
          SOILRESPGAT(K)  = SOILRESPROW(ILMOS(K),JLMOS(K))
          RMGAT(K)        = RMROW(ILMOS(K),JLMOS(K))
          RGGAT(K)        = RGROW(ILMOS(K),JLMOS(K))
          NBPGAT(K)       = NBPROW(ILMOS(K),JLMOS(K))
          LITRESGAT(K)    = LITRESROW(ILMOS(K),JLMOS(K))
          SOCRESGAT(K)    = SOCRESROW(ILMOS(K),JLMOS(K))
          GPPGAT(K)       = GPPROW(ILMOS(K),JLMOS(K))
          DSTCEMLSGAT(K)  = DSTCEMLSROW(ILMOS(K),JLMOS(K))
          LITRFALLGAT(K)  = LITRFALLROW(ILMOS(K),JLMOS(K))
          HUMIFTRSGAT(K)  = HUMIFTRSROW(ILMOS(K),JLMOS(K))
          RMLGAT(K)       = RMLROW(ILMOS(K),JLMOS(K))
          RMSGAT(K)       = RMSROW(ILMOS(K),JLMOS(K))
          RMRGAT(K)       = RMRROW(ILMOS(K),JLMOS(K))
          BURNFRACGAT(K)  = BURNFRACROW(ILMOS(K),JLMOS(K))
          PROBFIREGAT(K)  = PROBFIREROW(ILMOS(K),JLMOS(K))
          LUCEMCOMGAT(K)  = LUCEMCOMROW(ILMOS(K),JLMOS(K))
          LUCLTRINGAT(K)  = LUCLTRINROW(ILMOS(K),JLMOS(K))
          LUCSOCINGAT(K)  = LUCSOCINROW(ILMOS(K),JLMOS(K))
          GRCLAREAGAT(K)  = GRCLAREAROW(ILMOS(K),JLMOS(K))
          DSTCEMLS3GAT(K) = DSTCEMLS3ROW(ILMOS(K),JLMOS(K))
          FAREGAT(K)      = FAREROW(ILMOS(K),JLMOS(K))
          GAVGSCMSGAT(K)  = GAVGSCMSROW(ILMOS(K),JLMOS(K))
C 
C         FIRE EMISSION VARIABLES
          EMIT_CO2GAT(K)  = EMIT_CO2ROW(ILMOS(K),JLMOS(K))  
          EMIT_COGAT(K)   = EMIT_COROW(ILMOS(K),JLMOS(K))   
          EMIT_CH4GAT(K)  = EMIT_CH4ROW(ILMOS(K),JLMOS(K))  
          EMIT_NMHCGAT(K) = EMIT_NMHCROW(ILMOS(K),JLMOS(K)) 
          EMIT_H2GAT(K)   = EMIT_H2ROW(ILMOS(K),JLMOS(K))   
          EMIT_NOXGAT(K)  = EMIT_NOXROW(ILMOS(K),JLMOS(K))  
          EMIT_N2OGAT(K)  = EMIT_N2OROW(ILMOS(K),JLMOS(K))  
          EMIT_PM25GAT(K) = EMIT_PM25ROW(ILMOS(K),JLMOS(K)) 
          EMIT_TPMGAT(K)  = EMIT_TPMROW(ILMOS(K),JLMOS(K))  
          EMIT_TCGAT(K)   = EMIT_TCROW(ILMOS(K),JLMOS(K))   
          EMIT_OCGAT(K)   = EMIT_OCROW(ILMOS(K),JLMOS(K))   
          EMIT_BCGAT(K)   = EMIT_BCROW(ILMOS(K),JLMOS(K))  
 
100   CONTINUE
C
      DO 101 L=1,ICC
       DO 101 K=1,NML
          FCANCMXGAT(K,L)  = FCANCMXROW(ILMOS(K),JLMOS(K),L)
          AILCGGAT(K,L)    = AILCGROW(ILMOS(K),JLMOS(K),L)
          AILCGSGAT(K,L)   = AILCGSROW(ILMOS(K),JLMOS(K),L)
          FCANCSGAT(K,L)   = FCANCSROW(ILMOS(K),JLMOS(K),L)
          FCANCGAT(K,L)    = FCANCROW(ILMOS(K),JLMOS(K),L)
          CO2I1CGGAT(K,L)  = CO2I1CGROW(ILMOS(K),JLMOS(K),L)
          CO2I1CSGAT(K,L)  = CO2I1CSROW(ILMOS(K),JLMOS(K),L)
          CO2I2CGGAT(K,L)  = CO2I2CGROW(ILMOS(K),JLMOS(K),L)
          CO2I2CSGAT(K,L)  = CO2I2CSROW(ILMOS(K),JLMOS(K),L)
          SLAIGAT(K,L)     = SLAIROW(ILMOS(K),JLMOS(K),L)
          ANCSVEGGAT(K,L)  = ANCSVEGROW(ILMOS(K),JLMOS(K),L)
          ANCGVEGGAT(K,L)  = ANCGVEGROW(ILMOS(K),JLMOS(K),L)
          RMLCSVEGGAT(K,L) = RMLCSVEGROW(ILMOS(K),JLMOS(K),L)
          RMLCGVEGGAT(K,L) = RMLCGVEGROW(ILMOS(K),JLMOS(K),L)
          ANVEGGAT(K,L)    = ANVEGROW(ILMOS(K),JLMOS(K),L)
          RMLVEGGAT(K,L)   = RMLVEGROW(ILMOS(K),JLMOS(K),L)
          PFCANCMXGAT(K,L) = PFCANCMXROW(ILMOS(K),JLMOS(K),L)
          NFCANCMXGAT(K,L) = NFCANCMXROW(ILMOS(K),JLMOS(K),L)
          STEMMASSGAT(K,L) = STEMMASSROW(ILMOS(K),JLMOS(K),L)
          ROOTMASSGAT(K,L) = ROOTMASSROW(ILMOS(K),JLMOS(K),L)
          GLEAFMASGAT(K,L) = GLEAFMASROW(ILMOS(K),JLMOS(K),L)
          BLEAFMASGAT(K,L) = BLEAFMASROW(ILMOS(K),JLMOS(K),L)
          AILCBGAT(K,L)    = AILCBROW(ILMOS(K),JLMOS(K),L)
          FLHRLOSSGAT(K,L) = FLHRLOSSROW(ILMOS(K),JLMOS(K),L)
          PANDAYSGAT(K,L)  = PANDAYSROW(ILMOS(K),JLMOS(K),L)
          LFSTATUSGAT(K,L) = LFSTATUSROW(ILMOS(K),JLMOS(K),L)
          GRWTHEFFGAT(K,L) = GRWTHEFFROW(ILMOS(K),JLMOS(K),L)
          LYSTMMASGAT(K,L) = LYSTMMASROW(ILMOS(K),JLMOS(K),L)
          LYROTMASGAT(K,L) = LYROTMASROW(ILMOS(K),JLMOS(K),L)
          TYMAXLAIGAT(K,L) = TYMAXLAIROW(ILMOS(K),JLMOS(K),L)
          STMHRLOSGAT(K,L) = STMHRLOSROW(ILMOS(K),JLMOS(K),L)
          BMASVEGGAT(K,L)  = BMASVEGROW(ILMOS(K),JLMOS(K),L)
          ROTHRLOSGAT(K,L) = ROTHRLOSROW(ILMOS(K),JLMOS(K),L)
          VEGHGHTGAT(K,L)  = VEGHGHTROW(ILMOS(K),JLMOS(K),L)
          ROOTDPTHGAT(K,L) = ROOTDPTHROW(ILMOS(K),JLMOS(K),L)
          TLTRLEAFGAT(K,L) = TLTRLEAFROW(ILMOS(K),JLMOS(K),L)
          TLTRSTEMGAT(K,L) = TLTRSTEMROW(ILMOS(K),JLMOS(K),L)
          TLTRROOTGAT(K,L) = TLTRROOTROW(ILMOS(K),JLMOS(K),L)
          LEAFLITRGAT(K,L) = LEAFLITRROW(ILMOS(K),JLMOS(K),L)
          ROOTTEMPGAT(K,L) = ROOTTEMPROW(ILMOS(K),JLMOS(K),L)
          AFRLEAFGAT(K,L)  = AFRLEAFROW(ILMOS(K),JLMOS(K),L)
          AFRSTEMGAT(K,L)  = AFRSTEMROW(ILMOS(K),JLMOS(K),L)
          AFRROOTGAT(K,L)  = AFRROOTROW(ILMOS(K),JLMOS(K),L)
          WTSTATUSGAT(K,L) = WTSTATUSROW(ILMOS(K),JLMOS(K),L)
          LTSTATUSGAT(K,L) = LTSTATUSROW(ILMOS(K),JLMOS(K),L)
          NPPVEGGAT(K,L)   = NPPVEGROW(ILMOS(K),JLMOS(K),L)
          RMLVEGACCGAT(K,L)= RMLVEGACCROW(ILMOS(K),JLMOS(K),L)
          RMSVEGGAT(K,L)   = RMSVEGROW(ILMOS(K),JLMOS(K),L)
          RMRVEGGAT(K,L)   = RMRVEGROW(ILMOS(K),JLMOS(K),L)
          RGVEGGAT(K,L)    = RGVEGROW(ILMOS(K),JLMOS(K),L)
          GPPVEGGAT(K,L)   = GPPVEGROW(ILMOS(K),JLMOS(K),L)
          NEPVEGGAT(K,L)   = NEPVEGROW(ILMOS(K),JLMOS(K),L)
          AILCMINGAT(K,L)  = AILCMINROW(ILMOS(K),JLMOS(K),L)
          AILCMAXGAT(K,L)  = AILCMAXROW(ILMOS(K),JLMOS(K),L)
          VGBIOMAS_VEGGAT(K,L) = VGBIOMAS_VEGROW(ILMOS(K),JLMOS(K),L)
C
101   CONTINUE
C
      DO 102 L=1,ICC+1
       DO 102 K=1,NML
          LITRMASSGAT(K,L)=LITRMASSROW(ILMOS(K),JLMOS(K),L)
          SOILCMASGAT(K,L)=SOILCMASROW(ILMOS(K),JLMOS(K),L)
102   CONTINUE
C
      DO 105 L=1,12     !12 MONTHS
       DO 105 K=1,NML
          MLIGHTNGGAT(K,L)=MLIGHTNGGRD(ILMOS(K),L)
105   CONTINUE
C
      DO 106 L=1,2     !2 PFTs (NDL DCD & CROPs)
       DO 106 K=1,NML
          COLDDAYSGAT(K,L)=COLDDAYSROW(ILMOS(K),JLMOS(K),L)
106   CONTINUE
C
      DO 201 L=1,ICAN
       DO 201 K=1,NML
          AILCGAT(K,L)     = AILCROW(ILMOS(K),JLMOS(K),L)
          ZOLNCGAT(K,L)    = ZOLNCROW(ILMOS(K),JLMOS(K),L)
          CMASVEGCGAT(K,L) = CMASVEGCROW(ILMOS(K),JLMOS(K),L)
          PAICGAT(K,L)     = PAICROW(ILMOS(K),JLMOS(K),L)
          SLAICGAT(K,L)    = SLAICROW(ILMOS(K),JLMOS(K),L)
C
          ALVSCTMGAT(K,L)  = ALVSCTMROW(ILMOS(K),JLMOS(K),L)
          ALIRCTMGAT(K,L)  = ALIRCTMROW(ILMOS(K),JLMOS(K),L)
201   CONTINUE
C
      DO 250 L=1,IGND
       DO 250 K=1,NML
          SANDGAT(K,L) = SANDROW(ILMOS(K),JLMOS(K),L)
          CLAYGAT(K,L) = CLAYROW(ILMOS(K),JLMOS(K),L)
          ORGMGAT(K,L) = ORGMROW(ILMOS(K),JLMOS(K),L)
          TBARACCGAT_M(K,L) = TBARACCROW_M(ILMOS(K),JLMOS(K),L)
250   CONTINUE
C
      DO 280 L=1,ICC
       DO 280 M=1,IGND
        DO 280 K=1,NML
          RMATCTEMGAT(K,L,M) = RMATCTEMROW(ILMOS(K),JLMOS(K),L,M)
280   CONTINUE
C
      DO 290 L=1,ICAN
       DO 290 M=1,IGND
        DO 290 K=1,NML
          RMATCGAT(K,L,M) = RMATCROW(ILMOS(K),JLMOS(K),L,M)
290   CONTINUE
C

      RETURN
      END
